In [1]:
%pip install ultralytics


     -------------------------------------- 609.5/609.5 kB 9.7 MB/s eta 0:00:00


In [1]:
from ultralytics import YOLO

In [4]:
# Load a model
model = YOLO("./models/yolov8n-pose.pt")  # build a new model from scratch
# model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

results = model(source="./sample/workout.mp4", show=True, conf=0.3, save=True)



    WARNING  stream/video/webcam/dir predict source will accumulate results in RAM unless `stream=True` is passed,
    causing potential out-of-memory errors for large sources or long-running streams/videos.

    Example:
        results = model(source=..., stream=True)  # generator of Results objects
        for r in results:
            boxes = r.boxes  # Boxes object for bbox outputs
            masks = r.masks  # Masks object for segment masks outputs
            probs = r.probs  # Class probabilities for classification outputs

video 1/1 (1/1500) c:\Users\srika\github\Pose-Estimation-Ultralytics\sample\workout.mp4: 384x640 2 persons, 947.5ms
video 1/1 (2/1500) c:\Users\srika\github\Pose-Estimation-Ultralytics\sample\workout.mp4: 384x640 2 persons, 12.8ms
video 1/1 (3/1500) c:\Users\srika\github\Pose-Estimation-Ultralytics\sample\workout.mp4: 384x640 1 person, 16.5ms
video 1/1 (4/1500) c:\Users\srika\github\Pose-Estimation-Ultralytics\sample\workout.mp4: 384x640 1 person, 10.0ms


: 

In [2]:
# Load a model
model = YOLO("./models/yolov8n-pose.pt")  # build a new model from scratch
# model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

results = model(source="./resources/pose-img.jpg", show=True, conf=0.3)


image 1/1 c:\Users\srika\github\Pose-Estimation-Ultralytics\resources\pose-img.jpg: 352x640 1 person, 195.4ms
Speed: 2.0ms preprocess, 195.4ms inference, 5.4ms postprocess per image at shape (1, 3, 352, 640)


In [ ]:
for r in results:
    print(r.)

In [ ]:
import cv2
import numpy as np

# Load your image
image = cv2.imread("./resources\pose-img.jpg")
# Iterate through JSON data and draw bounding boxes and keypoints
for entry in results:
    box = entry["box"]
    keypoints = entry["keypoints"]

    x1, y1, x2, y2 = (
        int(box["x1"] * image.shape[1]),
        int(box["y1"] * image.shape[0]),
        int(box["x2"] * image.shape[1]),
        int(box["y2"] * image.shape[0])
    )

    # Draw bounding box
    cv2.rectangle(image, (x1, y1), (x2, y2), (0, 255, 0), 2)  # Green rectangle

    # Draw keypoints
    for x, y, vis in zip(keypoints["x"], keypoints["y"], keypoints["visible"]):
        x_pixel = int(x * image.shape[1])
        y_pixel = int(y * image.shape[0])

        if vis > 0.5:
            cv2.circle(image, (x_pixel, y_pixel), 5, (255, 0, 0), -1)  # Blue circle

# Show the image with bounding boxes and keypoints
cv2.imshow("Image with Bounding Boxes and Keypoints", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [40]:
for result in results:
   boxes = result.boxes  # Boxes object for bbox outputs
   masks = result.masks  # Masks object for segmenation masks outputs
   probs = result.probs  # Class probabilities
   print(boxes)
   print(masks)
   print(probs)


boxes = results[0].boxes
box = boxes[0]  # returns one box
box.xyxy
boxes.xyxy  # box with xyxy format, (N, 4)
boxes.xywh  # box with xywh format, (N, 4)
boxes.xyxyn  # box with xyxy format but normalized, (N, 4)
boxes.xywhn  # box with xywh format but normalized, (N, 4)
boxes.conf  # confidence score, (N, 1)
boxes.cls  # cls, (N, 1)
boxes.data  # raw bboxes tensor, (N, 6) or boxes.boxes .

WARNING  'Boxes.boxes' is deprecated. Use 'Boxes.data' instead.


ultralytics.engine.results.Boxes object with attributes:

boxes: tensor([[3.9500e+02, 5.5000e+01, 1.0570e+03, 6.1800e+02, 8.8660e-01, 0.0000e+00]], device='cuda:0')
cls: tensor([0.], device='cuda:0')
conf: tensor([0.8866], device='cuda:0')
data: tensor([[3.9500e+02, 5.5000e+01, 1.0570e+03, 6.1800e+02, 8.8660e-01, 0.0000e+00]], device='cuda:0')
id: None
is_track: False
orig_shape: (700, 1280)
shape: torch.Size([1, 6])
xywh: tensor([[726.0000, 336.5000, 662.0000, 563.0000]], device='cuda:0')
xywhn: tensor([[0.5672, 0.4807, 0.5172, 0.8043]], device='cuda:0')
xyxy: tensor([[ 395.,   55., 1057.,  618.]], device='cuda:0')
xyxyn: tensor([[0.3086, 0.0786, 0.8258, 0.8829]], device='cuda:0')
None
None


tensor([[3.9500e+02, 5.5000e+01, 1.0570e+03, 6.1800e+02, 8.8660e-01, 0.0000e+00]], device='cuda:0')

In [44]:
from ultralytics import YOLO
import cv2
import os

img = cv2.imread('temp_file.jpg')
path = "./sample"
if not os.path.exists(path):
    os.mkdir(path)

for result in results:
    boxes = result.boxes.cpu().numpy()
    for i, box in enumerate(boxes):
        r = box.xyxy[0].astype(int)
        crop = img[r[1]:r[3], r[0]:r[2]]
        filename = str(i) + ".jpg"
        if (box.conf[0] > 0.5):
            filename = os.path.join(path, filename)
        cv2.imwrite(filename, crop)

[ 395   55 1057  618]


In [5]:
for r in results:
    # print(r.tojson(normalize=True))
    # r.save_crop(save_dir='sample')
    r.save_txt(txt_file='sample/label.txt', save_conf=True)
    print(r.plot(conf=True, boxes=True))

[[[27 20 23]
  [27 20 23]
  [27 20 23]
  ...
  [18 12 13]
  [18 12 13]
  [18 12 13]]

 [[25 18 21]
  [25 18 21]
  [25 18 21]
  ...
  [18 12 13]
  [18 12 13]
  [18 12 13]]

 [[23 16 19]
  [23 16 19]
  [23 16 19]
  ...
  [18 12 13]
  [18 12 13]
  [18 12 13]]

 ...

 [[39 32 35]
  [39 32 35]
  [38 31 34]
  ...
  [65 59 64]
  [63 57 62]
  [62 56 61]]

 [[38 31 34]
  [37 30 33]
  [37 30 33]
  ...
  [64 58 63]
  [62 56 61]
  [60 54 59]]

 [[37 30 33]
  [36 29 32]
  [36 29 32]
  ...
  [64 58 63]
  [61 55 60]
  [59 53 58]]]


In [6]:
import cv2
import numpy as np

# Load the image
image_path = "./temp_file.jpg"
image = cv2.imread(image_path)

# Parse the text data
data = "0 0.567187 0.480714 0.517188 0.804286 0.381981 0.307469 0.987418 0.392637 0.283966 0.972952 0.373258 0.278593 0.931031 0.413253 0.27906 0.798184 0.355014 0.253344 0.525556 0.437644 0.366055 0.998456 0.348917 0.259386 0.983593 0.435123 0.559113 0.997389 0.382372 0.18928 0.965107 0.367334 0.726334 0.986622 0.434108 0.11644 0.940578 0.49978 0.509984 0.999507 0.404724 0.484731 0.99869 0.645067 0.633415 0.997067 0.356192 0.604764 0.993639 0.77724 0.775506 0.981639 0.353758 0.742143 0.972136 0.886602"
data = data.split()

# Convert the data into usable format
class_id = int(data[0])
box = list(map(float, data[1:5]))
keypoints = [float(x) for x in data[5:]]

# Draw bounding box
x1, y1, x2, y2 = [int(val * image.shape[1 if i % 2 == 0 else 0]) for i, val in enumerate(box)]
cv2.rectangle(image, (x1, y1), (x2, y2), (0, 255, 0), 2)

# Draw keypoints
for i in range(0, len(keypoints), 4):
    x = int(keypoints[i] * image.shape[1])
    y = int(keypoints[i + 1] * image.shape[0])
    visible = keypoints[i + 2]
    cv2.circle(image, (x, y), 3, (255, 0, 0), -1)

# Display the image
cv2.imshow("Image with Bounding Box and Keypoints", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
# import torch
# for r in results:
#     r = r.cpu().numpy()
#     r = r.to(device='cpu', dtype=torch.float32)
#     print(r.plot(pil=True))

In [11]:
import cv2
import numpy as np

# Assuming your results object is named 'results'
for r in results:
    image_array = r.plot(conf=True, boxes=True)

    # Convert the image_array to OpenCV format
    image_cv2 = np.array(image_array)
    image_cv2 = cv2.cvtColor(image_cv2, cv2.COLOR_RGB2BGR)  # Convert from RGB to BGR format

    # Display the image using OpenCV
    cv2.imshow("Image with Bounding Boxes and Keypoints", image_cv2)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [10]:
for r in results:
    print(dir(r))
    r.plot(conf=True, boxes=True, save_dir="sample")

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_keys', 'boxes', 'cpu', 'cuda', 'keypoints', 'keys', 'masks', 'names', 'new', 'numpy', 'orig_img', 'orig_shape', 'path', 'plot', 'probs', 'save_crop', 'save_dir', 'save_txt', 'speed', 'to', 'tojson', 'update', 'verbose']


In [3]:
import matplotlib.pyplot as plt
import numpy as np
import cv2
# Assuming your results object is named 'results'
for r in results:
    print(r.tojson(normalize=True))
    # r.save_crop(save_dir='sample')
    image_array = r.plot(conf=True, boxes=True)
    print(image_array)
    cv2.imwrite("model_write.png", image_array)
    # cv2.imshow("image", image_array)
    # # Display the image
    # plt.imshow(image_array)
    # plt.axis('off')  # Turn off axis numbers and ticks
    # plt.show()


[
  {
    "name": "person",
    "class": 0,
    "confidence": 0.8866015672683716,
    "box": {
      "x1": 0.30859375,
      "y1": 0.07857142857142857,
      "x2": 0.82578125,
      "y2": 0.8828571428571429
    },
    "keypoints": {
      "x": [
        0.3819807767868042,
        0.3926370441913605,
        0.3732582926750183,
        0.41325315833091736,
        0.3550143837928772,
        0.4376439154148102,
        0.34891653060913086,
        0.4351228177547455,
        0.38237208127975464,
        0.36733362078666687,
        0.4341079592704773,
        0.4997796416282654,
        0.4047237038612366,
        0.6450666189193726,
        0.3561919629573822,
        0.7772396206855774,
        0.3537580370903015
      ],
      "y": [
        0.30746933817863464,
        0.28396639227867126,
        0.278592586517334,
        0.2790604829788208,
        0.2533438503742218,
        0.366054505109787,
        0.2593860626220703,
        0.5591127872467041,
        0.18928022682666779,


: 

In [ ]:
cv2.imshow("image", img)